# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97041b77cb1769b00dafd05b5aac3ee680840e86e395bda130cc1c31ef444bb6c1b5e962c9ad0a31dfba1a64deec0263a0e2efe2b861d6a592bb3c63f0423bac

test:
  secret_key_base: a58e66bea7759c16b137b0d931aaca47b52854b33f5cb44ff7524f8a5ec9a4cbcbeac47996dd9329cb3099056628caf1954ae4990674a0d5e0ea0ab0ffb062f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
